name: Quality Assurance

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - '**.php'
      - 'phpunit.xml'
      - 'composer.json'
      - 'composer.lock'

jobs:
  composer:
    name: composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2

      - name: Validate composer.json and composer.lock 👀
        run: composer validate

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Check for outdated dependencies
        run: |
          if [ -n "$(composer outdated --direct --no-dev)" ]; then
            echo "❌ There are outdated dependencies!"
            composer outdated --direct
            exit 1
          fi
        shell: bash

  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          ini-values: memory_limit=1G
          tools: composer:v2

      - name: Install Dependencies 🔧
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run phpstan
        run: vendor/bin/phpstan analyse --no-progress

  rector:
    name: rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2

      - name: Install Dependencies 🔧
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run rector
        run: vendor/bin/rector process --dry-run
